Add dicom to sobp converter
DataMedSci/pymchelper pull request #563
Opened 2022-08-04 13:48 UTC by FardousR

Closes #384

2022-08-16 15:30 UTC, grzanka requested changes
first comments

2022-08-16 15:30 UTC, grzanka commented on pymchelper/utils/plan.py
> +    x: float
mention the units

2022-08-16 15:30 UTC, grzanka commented on pymchelper/utils/plan.py
> +    def load(self, file):
I'd suggest to move parsing method outside the class
```
def load_plan(fname: str) -> Plan:
   p = Plan()
   (....)
   return p
```

2022-08-18 14:57 UTC, grzanka commented on pymchelper/utils/dicom2sobp.py
> +        s += "{:.5f}".format(bm.f_e(en) / 1000.0)  # actual energy [GeV]
Consider using f-strings

```suggestion
        s += f"{bm.f_e(en) / 1000.0:.5f}"  # actual energy [GeV]
```

2022-11-28 20:56 UTC, nbassler commented on tests/test_plan.py
> +#     """Test plan loading with beam model."""
@grzanka need this :)

2022-11-28 20:57 UTC, nbassler commented on tests/test_plan.py
> +#     """Test plan loading with beam model."""
`-b tests/res/pld/beam_model_generic.csv tests/res/dicom/RN.1.2.246.352.71.5.361940808526.37240.20200311150225.dcm`

2022-12-02 20:17 UTC, grzanka approved these changes

2022-12-02 20:37 UTC, merged